# Update to check_www_servers.py
Added update to ping a host if it fails to connect to webserver.  So is the host down or just the service?

Added/modified the try section:


```python
	except urllib.error.URLError:
		print("Timeout connecting to: " + WWW + "   Port:" + WWWPORT + " down!")
		print("Trying to ping host:...")
		pingHost=str('ping -n 1 ' + server.strip())
		if not os.system(pingHost):
			# If return code 0, successful ping
			print("Host up, reponds to ping")
		else:
			# return is 1, ping failed
			print("Host down!!!")
```

New output:
```
Timeout connecting to: https://foo:9088   Port:9088 down!
Trying to ping host:...

Pinging foo [n.n.n.n] with 32 bytes of data:
Reply from n.n.n.n: bytes=32 time=1ms TTL=60

Ping statistics for n.n.n.n:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 1ms, Average = 1ms
Host up, reponds to ping
```


Update script posted in Github
